"""migrate_002

Revision ID: 1e127a06674d
Revises: 1cc78c8b43c1
Create Date: 2026-09-23 16:37:30.922079

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e127a06674d"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "1cc78c8b43c1"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


currency_enum = postgresql.ENUM("NGN", name="currency_enum")
trust_state = postgresql.ENUM("verified", "building", "new", "review", name="trust_state")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("email", sa.VARCHAR(length=255), nullable=True),
        sa.Column("google_id", sa.VARCHAR(length=255), nullable=True),
        sa.Column("google_email", sa.VARCHAR(length=255), nullable=True),
        sa.Column("business_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("paystack_integration_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("paystack_secret_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="merchants_pk"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_email"),
        sa.UniqueConstraint("google_id"),
        sa.UniqueConstraint("paystack_integration_id"),
    )
    op.create_table(
        "customers",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), nullable=True),
        sa.Column("phone", sa.VARCHAR(length=50), nullable=True),
        sa.Column("paystack_customer_code", sa.VARCHAR(length=100), nullable=True),
        sa.Column("total_transactions", sa.INTEGER(), nullable=False),
        sa.Column("total_spent", sa.BIGINT(), nullable=False),
        sa.Column("total_outstanding", sa.BIGINT(), nullable=False),
        sa.Column("total_disputes", sa.INTEGER(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="customers_pk"),
    )
    op.create_table(
        "merchant_settings",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("notification_whatsapp", sa.VARCHAR(length=50), nullable=True),
        sa.Column("notification_email", sa.BOOLEAN(), nullable=False),
        sa.Column("auto_reconciliation_tier1", sa.BOOLEAN(), nullable=False),
        sa.Column("default_reconciliation_range", sa.INTEGER(), nullable=False),
        sa.Column("trust_public_enabled", sa.BOOLEAN(), nullable=False),
        sa.Column("trust_widget_enabled", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="merchant_settings_pk"),
        sa.UniqueConstraint("merchant_id"),
    )
    op.create_table(
        "reconciliation_sessions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("date_range_start", sa.DATE(), nullable=False),
        sa.Column("date_range_end", sa.DATE(), nullable=False),
        sa.Column("total_transactions", sa.INTEGER(), nullable=False),
        sa.Column("matched_count", sa.INTEGER(), nullable=False),
        sa.Column("unmatched_payments_count", sa.INTEGER(), nullable=False),
        sa.Column("unmatched_orders_count", sa.INTEGER(), nullable=False),
        sa.Column("flagged_count", sa.INTEGER(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("in_progress", "completed", name="reconciliation_session_status"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="reconciliation_sessions_pk"),
    )
    op.create_table(
        "trust_profiles",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column(
            "current_state",
            trust_state,
            nullable=False,
        ),
        sa.Column("internal_score", sa.INTEGER(), nullable=True),
        sa.Column("reconciliation_rate", sa.FLOAT(), nullable=True),
        sa.Column("fulfillment_rate", sa.FLOAT(), nullable=True),
        sa.Column("dispute_rate", sa.FLOAT(), nullable=True),
        sa.Column("dispute_win_rate", sa.FLOAT(), nullable=True),
        sa.Column("avg_response_time_pct", sa.FLOAT(), nullable=True),
        sa.Column("evidence_readiness_avg", sa.FLOAT(), nullable=True),
        sa.Column("public_token", sa.VARCHAR(length=64), nullable=False),
        sa.Column("last_computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="trust_profiles_pk"),
        sa.UniqueConstraint("merchant_id"),
        sa.UniqueConstraint("public_token"),
    )
    op.create_table(
        "trust_snapshots",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            trust_state,
            nullable=False,
        ),
        sa.Column("internal_score", sa.INTEGER(), nullable=True),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="trust_snapshots_pk"),
    )
    op.create_table(
        "orders",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("order_number", sa.VARCHAR(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.BIGINT(), nullable=False),
        sa.Column("currency", currency_enum, nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "paid",
                "partially_paid",
                "fulfilled",
                "cancelled",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "website",
                "whatsapp",
                "instagram",
                "in_store",
                "other",
                name="order_source",
            ),
            nullable=False,
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="orders_pk"),
    )
    op.create_table(
        "transactions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("paystack_transaction_id", sa.BIGINT(), nullable=False),
        sa.Column("paystack_reference", sa.VARCHAR(length=100), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.BIGINT(), nullable=False),
        sa.Column("currency", currency_enum, nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "card",
                "bank_transfer",
                "mobile_money",
                "ussd",
                name="transaction_channel",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "failed",
                "queued",
                "pending",
                "ongoing",
                "success",
                "rejected",
                "reversed",
                "initiated",
                "abandoned",
                "processing",
                name="transaction_status",
            ),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paystack_fees", sa.BIGINT(), nullable=True),
        sa.Column("customer_email", sa.VARCHAR(length=255), nullable=True),
        sa.Column("customer_name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "reconciliation_status",
            sa.Enum(
                "unmatched",
                "auto_matched",
                "manually_matched",
                "flagged",
                name="reconciliation_status",
            ),
            nullable=False,
        ),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="transactions_pk"),
    )
    op.create_index(
        op.f("ix_transactions_paystack_reference"),
        "transactions",
        ["paystack_reference"],
        unique=True,
    )
    op.create_table(
        "disputes",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("paystack_dispute_id", sa.BIGINT(), nullable=False),
        sa.Column("paystack_reference", sa.VARCHAR(length=100), nullable=False),
        sa.Column("amount", sa.BIGINT(), nullable=False),
        sa.Column("currency", currency_enum, nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "chargeback_no_value",
                "chargeback_not_as_described",
                "fraud",
                "admin_error",
                "unknown",
                name="dispute_category",
            ),
            nullable=True,
        ),
        sa.Column("category_confidence", sa.FLOAT(), nullable=True),
        sa.Column("paystack_category", sa.VARCHAR(length=50), nullable=True),
        sa.Column("reason_raw", sa.Text(), nullable=True),
        sa.Column(
            "submission_flow",
            sa.Enum("chargeback_flow", "fraud_flow", name="submission_flow"),
            nullable=True,
        ),
        sa.Column("paystack_evidence_id", sa.INTEGER(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "evidence_generated",
                "submitted",
                "won",
                "lost",
                "auto_accepted",
                name="dispute_status",
            ),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_narrative", sa.Text(), nullable=True),
        sa.Column("evidence_pdf_url", sa.Text(), nullable=True),
        sa.Column("evidence_quality_score", sa.FLOAT(), nullable=True),
        sa.Column(
            "evidence_suggestions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.VARCHAR(length=20), nullable=True),
        sa.Column("paystack_resolution", sa.VARCHAR(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="disputes_pk"),
    )
    op.create_table(
        "fulfillments",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "delivery",
                "service_completed",
                "digital_download",
                "in_store_pickup",
                name="fulfillment_type",
            ),
            nullable=False,
        ),
        sa.Column("delivery_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tracking_number", sa.VARCHAR(length=255), nullable=True),
        sa.Column("recipient_name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column("proof_photo_url", sa.Text(), nullable=True),
        sa.Column("proof_document_url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="fulfillments_pk"),
    )
    op.create_table(
        "dispute_evidence_files",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("dispute_id", sa.UUID(), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum(
                "receipt",
                "delivery_photo",
                "tracking_doc",
                "signed_confirmation",
                "other",
                name="evidence_file_type",
            ),
            nullable=False,
        ),
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column("file_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dispute_id"],
            ["disputes.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="dispute_evidence_files_pk"),
    )
    op.create_table(
        "notifications_log",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("dispute_id", sa.UUID(), nullable=True),
        sa.Column(
            "channel",
            sa.Enum("whatsapp", "email", name="notification_channel"),
            nullable=False,
        ),
        sa.Column(
            "message_type",
            sa.Enum(
                "dispute_alert",
                "deadline_warning",
                "evidence_ready",
                "reconciliation_summary",
                "dispute_resolved",
                name="notification_message_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("sent", "failed", "pending", name="notification_status"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["dispute_id"],
            ["disputes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id", name="notifications_log_pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notifications_log")
    op.drop_table("dispute_evidence_files")
    op.drop_table("fulfillments")
    op.drop_table("disputes")
    op.drop_index(op.f("ix_transactions_paystack_reference"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("orders")
    op.drop_table("trust_snapshots")
    op.drop_table("trust_profiles")
    op.drop_table("reconciliation_sessions")
    op.drop_table("merchant_settings")
    op.drop_table("customers")
    op.drop_table("merchants")
    # ### end Alembic commands ###
