"""migrate_003

Revision ID: b0a5f6be9cf6
Revises: 1e127a06674d
Create Date: 2026-09-25 02:20:25.013400

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0a5f6be9cf6"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "1e127a06674d"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("merchants", "paystack_secret_key", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("merchants", "paystack_secret_key", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
